### ISSUE TITLE
broken dependency reference

### ISSUE THREAD

**Issue by demotodo** [feuyeux/jax-rs2-guide-II#1]
The file (5.jaxrs2-client/pom.xml) includes broken dependency reference.

> ```
>   <dependency>
>       <groupId>com.example</groupId>
>       <artifactId>example-common</artifactId>
>       <version>1.0-SNAPSHOT</version>
>   </dependency>
> ```

Also redundant import (import org.springframework.boot.actuate.system.ApplicationPidFileWriter; and import javax.ws.rs.container.PreMatching;) in file (com.example.BootConsulApplication).
And redundant import (import javax.persistence.*;) in file (com.example.client.entity.Book).

**Comment by feuyeux** [comment]
fix now.
