### ISSUE TITLE
the issues of 4.4.sse->src->test/java/com/examples/sse->SseBroadcaseTest.java

### ISSUE THREAD

**Issue by JyzForCqupt** [feuyeux/jax-rs2-guide-II#6]
There may be some issues because the "for loop" does not call the method "doneLatch.countDown", and the main thread will be suspended forever. In a word, it seems that the callback function has been losted. Should it be like this:
`        for (int i = 0; i < MAX_COUNT; i++) {
            final WebTarget endpoint = target().path("broadcast/book").queryParam("clientId", i + 1);
            readerEventSources[i] = EventSource.target(endpoint).build();
            readerEventSources[i].register(new EventListener(){
             @Override
                public void onEvent(InboundEvent inboundEvent)
                {
                    try{
                        String data = inboundEvent.readData(String.class);
                        System.out.println("What the server response: " + inboundEvent.getId() + " : " +inboundEvent.getName() + " : " + data);
                        Assert.assertEquals(newBookName,data);
                        doneLatch.countDown();
                    }catch (ProcessingException e){
                        System.out.println(e.getMessage());
                    }
                }
});
}`

**Comment by feuyeux** [comment]
Cool! I fixed it accordingly, thanks.

```java
for (int i = 0; i < MAX_COUNT; i++) {
    final WebTarget endpoint = target().path("broadcast/book").queryParam("clientId", i + 1);
    readerEventSources[i] = EventSource.target(endpoint).build();
    readerEventSources[i].register(new EventListener() {
        @Override
        public void onEvent(InboundEvent inboundEvent) {
            try {
                String data = inboundEvent.readData(String.class);
                log.info("Response[{}]: {}", inboundEvent.getId(), data);
                Assert.assertEquals(newBookName, data);
                doneLatch.countDown();
            } catch (ProcessingException e) {
                System.out.println(e.getMessage());
            }
        }
    });
    readerEventSources[i].open();
}
```
